### ISSUE TITLE
Error: The system cannot find the path specified: 'projects'

### ISSUE THREAD

**Issue by thanhtamns** [adithya-s-k/Storyblocks#7]
Hi Mate,

I'm getting this error when starting from runStoryblocks.py
![image](https://github.com/adithya-s-k/Storyblocks/assets/14258304/fc01b809-b7d1-4905-9c89-e5c38423f4eb)

And I want to ask which API KEYS do I need to add to the project?
I've been searching but the project seems to lack a place to configure the API if needed?

**Comment by Sifiz** [comment]
got same issue

**Comment by Sifiz** [comment]
nevermind just create "projects" folder in Storyblocks

**Comment by thanhtamns** [comment]
> nevermind just create "projects" folder in Storyblocks

I created a "projects" folder but the code still crashes.
Are there any other files inside the "projects" folder?
![image](https://github.com/adithya-s-k/Storyblocks/assets/14258304/e12e1e81-3f3d-4d1d-ac59-277a7af0445a)

**Comment by adithya-s-k** [comment]
@thanhtamns @Sifiz hey i have fixed the bug. Check it out 
The "projects" folder should be placed in the root directory

**Comment by thanhtamns** [comment]
thanks so much

**Comment by adithya-s-k** [comment]
I am still working on the image generator. Trying to add something locally. Will most prabably finish within this week

**Comment by thanhtamns** [comment]
Nice to know that. I will wait

**Comment by thanhtamns** [comment]
Hey Mate,

Do you have plans to upload a new version?

**Comment by adithya-s-k** [comment]
@thanhtamns Yep a major update is coming soon 2 to 3 more days

**Comment by thanhtamns** [comment]
thanks so much
